language: cpp

sudo: false

matrix:
  include:
    - os: linux
      env:
      addons:
        apt:
          packages:
           - autoconf
           - automake
           - libtool
           - libgmp-dev
           - libglpk-dev
           - libntl-dev
           - libcdd-dev
           - libcdd-test
      before_script:
       - PATH="/usr/lib/cdd-test:$PATH"; export PATH

script:
  - ./.travis-build.sh
